name: PlatformIO CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e esp32release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: .pio/build/esp32release/firmware.bin
          
      - name: Build PlatformIO Project
        run: pio run -e esp32debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: .pio/build/esp32debug/firmware.bin
